### ISSUE TITLE
panic: spireg: no port found; did you forget to call Init()?

### ISSUE THREAD

**Issue by zangaby** [kubesail/pibox-framebuffer#7]
Hello,

Unfortunately the framebuffer would not start using the latest Raspberry Pi OS.

`pi@pibox:~ $ /opt/kubesail/pibox-framebuffer
panic: spireg: no port found; did you forget to call Init()?

goroutine 1 [running]:
github.com/kubesail/pibox-framebuffer/pkg.(*PiboxFrameBuffer).openFrameBuffer(0x2b6350?)
	/root/code/pibox-framebuffer/pkg/framebuffer.go:42 +0x5c
github.com/kubesail/pibox-framebuffer/pkg.(*PiboxFrameBuffer).Splash(0x3563b5?)
	/root/code/pibox-framebuffer/pkg/framebuffer.go:287 +0x1c
main.main()
	/root/code/pibox-framebuffer/cmd/main.go:38 +0x188`

**Comment by zangaby** [comment]
All good after 
` curl -s https://raw.githubusercontent.com/kubesail/pibox-os/main/update-framebuffer.sh | sudo bash`
